services:
  - type: web
    name: cafeflow-backend
    runtime: node
    rootDir: backend
    buildCommand: cd ../frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 4000
      - key: VITE_API_URL
        value: ""
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_FROM
        value: "angeldavidagudelocuartas13@gmail.com"
